import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import { Providers } from './providers';
import '../theme/globals.css';
import '@radix-ui/themes/styles.css';
import { Footer, Header } from '@/components';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="light">
      <body className={inter.className}>
        {/* maybe we can delete flex? */}
        <div className="min-h-screen flex flex-col">
          <Header />
          <main className="flex-1 overflow-y-auto p-4 max-w-screen-2xl  md:mx-auto">
            <Providers>{children}</Providers>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
